# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc007a5c342933ff2e9dfa8842e82339b56ff552f8c8ad6ba4d4f88882220bb8c0ef34718bb7df52f19534dcde57ee719341a56040c60e2c194180357db2fadd

test:
  secret_key_base: f37e997bc4a6c8a819ca88ada7256a62f9c7cc2e00a631aeb10ce2bce4b206c5065289d6b5b5d39dc78e9a8a78a85f6532650e779db1cadd973671d28a72a323

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
